### ISSUE TITLE
Terms Admin Feedback

### ISSUE THREAD

**Issue by rootelement** [topcoder-platform/admin-app#152]
These comments are as of this commit:
https://github.com/topcoder-platform/admin-app/commit/9290aa1982cc515da452fd332422014d700f7ce2

## /index/terms/list
1. Take out Legacy ID as a filter.
2. Filters should be
  - Title (name search)
3. Change List View
  - Columns should be Title (clickable to view/edit), Agreeability Type, Info, [Delete Terms]
  - Info column should be based on Agreeability Type. If it's Electronic, it should show the URL. If it's Docusignable, it should show the Docusign UUID

## /index/terms/new
1. Take out Legacy ID
2. Group Agreeability Type, Docusign Template ID, and URL together. If Agreeability Type === Electronically Signable, show the URL field. If it === Docusign, show the Docusign Template ID.
3. What is Type ID?

Questions:
1. Should Text for the terms be a rich text field?

**Comment by maxceem** [comment]
@rootelement

## /index/terms/list

1. > Filters should be: 
       Title (name search)

    Terms Service at the moment only supports filtering by `legacyId`, see [source code](https://github.com/topcoder-platform/terms-service/blob/dev/src/services/TermsOfUseService.js#L453) and [swagger screenshot](https://monosnap.com/file/lJaSj73cP8bTjyVaXtirhZjoL1T1JI).

    Should I log an issue for the Terms Service team to implement this, or should we handle this change in the Terms Service as a part of this task?

2.  > Info column should be based on Agreeability Type. If it's Electronic, it should show the URL. If it's Docusignable, it should show the Docusign UUID

     In case **Agreeability Type** has another value like `Non-agreeable` or `Non-electronically-agreeable` the **Info** column would be empty, right?

## /index/terms/new

3. > What is Type ID?

    Unfortunately I don't know the meaning of this field, but it is required in the `TermsOfUse` model https://github.com/topcoder-platform/terms-service/blob/dev/src/models/TermsOfUse.js#L11

4. > Should Text for the terms be a rich text field?

    I can see mostly `text` field has HTML format (example terms of use id `33d53c6b-ebee-45bd-b16b-2b843c12d70a`), but sometimes it can be markdown like in terms of use with id `05a25439-1b0a-4b57-9c2a-ecda94648f92`.

    If we can agree on the same format for all the terms of use, then we can use some RichTextEditor.

**Comment by rootelement** [comment]
1. Yes, please add an issue for the filters you need
2. Correct, it should be empty
3. Yes, it should be populated like that dropdown. Please create an issue on terms to create a related table of types. I will add to that issue with the types from the old admin.
4. Yes, we should have a html/markdown editor if possible.

**Comment by maxceem** [comment]
> Yes, we should have a html/markdown editor if possible.

@rootelement we can have an editor but we would have to choose one format `HTML` or `markdown`. As most of the Terms use HTML format, I suggest using `HTML` format as output. To be able to edit `markdown` we can add a button to disable RichText editor so we can edit the terms text as a plain text.

We can also try supporting both formats `HTML` and `markdown` by adding a switch between them. Though it might bring confusion and more edge cases to support. We can add such support later if admins feel the need for it.

**Comment by maxceem** [comment]
Done in PR https://github.com/topcoder-platform/admin-app/pull/139

**Comment by rootelement** [comment]
Looks good. I'm going to open a new issue for a few more tweaks. This is complete.
