### ISSUE TITLE
Auth0: V2 calls result in Invalid algorithm error (moved to Admin tool repo)

### ISSUE THREAD

**Issue by lakshmiathreya** [topcoder-platform/admin-app#157]
<img width="1606" alt="Screenshot 2020-10-22 at 11 02 50 AM" src="https://user-images.githubusercontent.com/51733042/96828940-2a0a6780-1456-11eb-97a9-2d08417c858d.png">

**Comment by sachin-maheshwari** [comment]
@mtwomey v2 calls are not supported for "new auth" (RS256 algo). So we need to change the v2 call,  no other go.

**Comment by sachin-maheshwari** [comment]
@nkumar-topcoder lets discuss with @RiteshTC to understand the priority for same.

**Comment by nkumar-topcoder** [comment]
@sachin-maheshwari @lakshmiathreya @mtwomey This has been discussed with Ritesh and feature is not at all used. hence, has no impact if left as is.
This can be closed.
