### ISSUE TITLE
Terms Admin - Final Tweaks

### ISSUE THREAD

**Issue by rootelement** [topcoder-platform/admin-app#161]
## List View

- [x] Remove the Delete Terms and Add User buttons
- [x] Add "Type" between Title and Agreeability Type

## Add Terms

- [x] Move Agreeability Type above the Text editor.
- [x] Decrease the height over the Text area to about half height.
- [x] Change "Type Id" to just Type. Select "Contest" by default.

## Edit Terms
- [x] Same edits as Add Terms
- [x] In the bottom left corner of the page (opposite the Save Changes button), put the count of users who have signed those terms. "3,200 Users have Signed". If that number is 0, show a Delete Terms button. You can only delete terms if nobody has signed them. When you delete the terms, take the user back to the list page.

## View Users
- [ ] Add the title of the terms to the top of the page. If you have multiple pages open or leave it open, you may not remember which terms you're viewing users for.

**Comment by maxceem** [comment]
@rootelement  Got it, will handle it via private task.

Would you like to add a couple of more tweaks?
1. When there are more than 0 users signed the terms, we can still show `Delete Terms` button but `disabled`. So we are aware that terms can be removed.
2. When we click `Delete Terms` button, show confirmation modal before removing it.

**Comment by rootelement** [comment]
Yes please. Sounds good

**Comment by anonymousjaggu** [comment]
> Add "Type" between Title and Agreeability Type
@maxceem  What do we mean by `Type`?

**Comment by rootelement** [comment]
I'm pushing a fix for this. It's deploying now. It will be called `type` @anonymousjaggu . Will post again when it's deployed and tested.

**Comment by maxceem** [comment]
@rootelement I will update when it's deployed.

**Comment by maxceem** [comment]
@rootelement it's deployed, but it's called `TermsOfUseType.type`:

![image](https://user-images.githubusercontent.com/146016/97312439-2750ad80-186e-11eb-82ca-b90095461fa5.png)

Would you like to rename it first?

**Comment by rootelement** [comment]
I'm renaming it. Deploying now

**Comment by maxceem** [comment]
@rootelement all done in PR https://github.com/topcoder-platform/admin-app/pull/163

**Comment by rootelement** [comment]
Fixed:
```json
{
            "id": "08d12659-abb9-450e-86a4-78b698bfdfcd",
            "legacyId": 20723,
            "title": "Subcontractor Services Agreement 2009-09-02",
            "url": "http://www.topcoder.com/i/terms/Subcontractor+Services+Agreement+2009-09-02.pdf",
            "agreeabilityTypeId": "208779bf-72ce-4e97-a398-13fa62c0414a",
            "agreeabilityType": "Non-electronically-agreeable",
            "type": "Contest"
        }
```
