### ISSUE TITLE
v5 Challenge Admin

### ISSUE THREAD

**Issue by rootelement** [topcoder-platform/admin-app#164]
Create a tool to manage v5 Challenges

Add a new menu item called  `v5 Challenge Management`. You can use the same icon.

## List view

List challenges (`GET https://api.topcoder-dev.com/v5/challenges` Auth: User JWT). Don't populate the list until the user clicks "Search".

Table should be:

Title | Status | # Registrants | # Submissions 
---|---|---|---

Do not worry about editing challenges yet. For now, just add a button at the end of each row that says "Manage Users"

Filters should be:
1. Challenge ID (v5 uuid) - Challenge filter (to be consistent with a list response) `?id=<v5 uuid>`
2. Legacy ID - Challenge filter `?legacyId=<legacyId>`
3. Type (`GET https://api.topcoder-dev.com/v5/challenge-types` Challenge filter `?types[]=<challengeTrack.abbreviation>`)
4. Track (`GET https://api.topcoder-dev.com/v5/challenge-tracks` Challenge filter `?tracks[]=<challengeType.abbreviation>`)
5. Status (ENUM New, Draft, Active, Completed) - default to Active - Challenge filter `?status=<status>`

## Detail View
Clicking on the Title of a challenge should show a View page. This should just list out the raw properties. For now, I'm fine if it's just a straight `<dl>` of the properties.
There should be a "Manage Users" button on this page as well. Somewhere logical.

## Manage Users
Show the challenge title at the top of the page
List the users with this table (`GET https://api.topcoder-dev.com/v5/resources?challengeId=<uuid>` Auth: User JWT)

Handle | Role | Registered
---|---|---

1. Populate the roles (`GET https://api.topcoder-dev.com/v5/resource-roles`) and map them to the IDs in the response objects (to display the name)
2. Registered date should be from the `created` property from the challenge object

Actions
1. Add a User - button that pops a modal (like add user to terms you just did)
   1. Handle (lookup field)
   2. Role (select dropdown)
2. Delete a User - A button at the end of each row of the list. Pops a "Are you Sure?" confirmation.

**Comment by rootelement** [comment]
Basically replacing this functionality in OR:
![Screen Shot 2020-10-27 at 4 10 52 PM](https://user-images.githubusercontent.com/5400156/97356698-0046ab80-186f-11eb-9ecc-8ba0f06976bc.png)

**Comment by maxceem** [comment]
@rootelement 

1. Did I get it right, that we are replacing the current section "Challenge Management" so **all existent** code which we don't need related to this section could be removed?

**Comment by rootelement** [comment]
Can you actually get it to work in dev? I couldn't even get it to look up a legacy id. I guess create a new section and call it v5 Challenge Management? That way we can create the new tool and phase out the old one... if it works at all.

**Comment by rootelement** [comment]
Ok, strange, it works in prod, but not in dev. Yes, leave that there as it is. Name the new section v5 Challenge Management. 
Best case scenario, we can either link to, or port over, those actions into our v5 management as we go.

**Comment by maxceem** [comment]
No, I've tried to search by both old and new challenge id, but the current tool didn't give me any results. Maybe something with the gateway on DEV:

![image](https://user-images.githubusercontent.com/146016/97358564-191d8400-18a4-11eb-83ff-54cd16d4097b.png)

**Comment by rootelement** [comment]
Well, i tested. it works in prod. Maybe it should be using v4. Don't worry about it, leave it as it is.

**Comment by maxceem** [comment]
Code challenge is launched to complete this task https://www.topcoder.com/challenges/63758f25-8587-4462-b746-14c4bad24150.

End date: `November 6`.

**Comment by maxceem** [comment]
@rootelement we've got the winning submission it perfectly matches the requirements IMO.

PR to DEV https://github.com/topcoder-platform/admin-app/pull/170.

**Comment by rootelement** [comment]
This is great, but I think we actually need to update the resource api so that admins can manage users/resources on a challenge. I can't add a submitter if the phase isn't opened for example. @ThomasKranitsas Can you give this a test:
https://admin.topcoder-dev.com and play around with the v5 challenge tool?
