### ISSUE TITLE
Billing Account Admin View

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/admin-app#46]
We need to add a view in the admin app to manage customer records, billing accounts, and resources on billing accounts.

This will manage the following tables in the time_oltp database:

client
project
project_manager

The API will handle the DB interactions, and @skyhit is managing that part.  For this story, we need the UI built within the admin tool.  Here is what an admin user needs to be able to do:

1. Create a new client
2. Edit a client
3. Create a new billing account
4. Edit a billing account
5. Add a resource to a billing account
6. Remove a resource from a billing account

Client properties:
- name
- status
- start date
- end date
- code name

Billing account properties:
- name
- description
- status
- po number
- payment terms
- start date
- end date
- subscription number

Resource properties:
- user
- status

In the admin tool, admins should be able to manage the above objects as well as the relationships between then.

Admin should be able to search and filter billing accounts easily by client name, start date, end date, status, billing account name, subscription number, user

**Comment by huangqun** [comment]
This is done.
