### ISSUE TITLE
Add Connect Role support to Admin App

### ISSUE THREAD

**Issue by parthshah** [topcoder-platform/admin-app#59]
Admin app , role management supports adding roles for Studio & TC roles. Let's enhance it to support adding / removing for TC Identity roles (Topcoder User, Connect Manager, Connect copilot)

@sudoster @ykohata  could you please link APIs for role management here. Thanks

**Comment by parthshah** [comment]
https://github.com/appirio-tech/tc1-api-core/blob/dev/tech.core/tech.core.service.identity/apiary.apib#L1126

**Comment by huangqun** [comment]
@parthshah is there a test service on dev server I can use for testing? If so what's the endpoint?
Thanks!

**Comment by ajefts** [comment]
@huangqun I believe you should be able to hit those /roles endpoints in dev at api.topcoder-dev.com/v3/roles/.  Let us know if that's not working.

**Comment by huangqun** [comment]
Keep getting this error when trying to invoke the api:
{
  "id": "-23d69c87:15977d8f722:-a65",
  "result": {
    "success": true,
    "status": 401,
    "metadata": null,
    "content": "Valid credentials are required to access this resource."
  },
  "version": "v3"
}

I used the token for user TonyJ which should be an admin token already right?

**Comment by huangqun** [comment]
Never mind, looks like I used a v2 token instead of v3.

**Comment by huangqun** [comment]
@parthshah @ajefts  is there an endpoint to get a list of users by these 3 new roles?

**Comment by ajefts** [comment]
Looks like this would do it:

https://github.com/appirio-tech/tc1-api-core/blob/dev/tech.core/tech.core.service.identity/apiary.apib#L1082

(Fetch All Subjects With Given Role [GET /roles/{roleId}/subjects])

**Comment by huangqun** [comment]
Done in https://github.com/topcoder-platform/admin-app/pull/70
