### ISSUE TITLE
Issue with managing roles from user page

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/admin-app#82]
For any user, it's showing all roles when you try to edit their roles and the Role drowdown is disabled.  It's showing all roles for all users, even if they aren't in those roles.

![image](https://user-images.githubusercontent.com/3812270/27644516-c6b29b3c-5bf1-11e7-95c4-ed2381f026cf.png)

**Comment by ajefts** [comment]
@huangqun Can you take a look at this one please?

Thanks.

**Comment by huangqun** [comment]
@ajefts were you testing on https://admin.topcoder-dev.com/? But when I tried why was it redirecting to accounts.topcoder.com the production site?

**Comment by ajefts** [comment]
@huangqun let me update that build param in CircleCI.  We still need to get that fixed so we don't need to edit it...

**Comment by ajefts** [comment]
fyi, it's redeployed to dev

**Comment by huangqun** [comment]
@ajefts this is what I saw on dev server when I tested:

![image](https://user-images.githubusercontent.com/6045894/27668088-88fa549a-5cb1-11e7-8a31-3b563b5a043d.png)


Could you please double check if you still see the issue too?

**Comment by ajefts** [comment]
Hrm...I see it ok in dev, but not prod.  The API call seems to return all roles, even with the subjectID filter in prod.

@ykohata We're making calls like https://api.topcoder.com/v3/roles/?filter=subjectID=8544935 with the bearer token from the admin tool.  It's returning all roles in prod.  Any ideas?

**Comment by huangqun** [comment]
My guess is the prod server is not running the latest code yet, but let's wait for @ykohata to confirm.

**Comment by ykohata** [comment]
@huangqun - could you tell me what PR should be deployed for this feature?

**Comment by huangqun** [comment]
It should came from either https://github.com/appirio-tech/tc1-api-core/pull/262 or https://github.com/appirio-tech/tc1-api-core/pull/263

**Comment by ykohata** [comment]
@huangqun - they have not been deployed in the production yet. I'm going to release them from now.

**Comment by ykohata** [comment]
done deploying these PRs in the production.
