### ISSUE TITLE
Add ability to create group via admin tool

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/admin-app#87]
In admin.topcoder.com, include the ability to create a new group.  This should do 2 things on the backend:

1. use the groups api to create the group in the Authorization DB groups table.
2. create the same group in informix in common_oltp:security_groups

**Comment by ajefts** [comment]
@huangqun fyi

**Comment by huangqun** [comment]
@ajefts for #1 I think we can use the existing groups api, but for #2 it looks like we'll need a new endpoint, should we put that into the identity service too?

**Comment by ajefts** [comment]
Yes, please.

**Comment by huangqun** [comment]
@ajefts I think this one can be closed now.
