### ISSUE TITLE
Add sso management to user lookup

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/admin-app#88]
When you look up a user in the admin tool, let's add the following features:

1. Display if the user is an SSO user and the provider (provider is based on the provider type)
2. In the Edit dropdown, add an item for SSO.  When selected, this should allow us to edit the user_sso_login record if the user is already an SSO user.  If the user is not an SSO user, then it should allow us to add a user_sso_login record.

We may need to add/modify endpoints to manage the sso records.

**Comment by huangqun** [comment]
@ajefts which service / microservice should we put in the new endpoints here?

**Comment by ajefts** [comment]
Identity service

**Comment by huangqun** [comment]
This one can be closed I think.
